call plug#begin('~/.vim/plugged')
     Plug 'preservim/nerdtree'
     Plug 'vim-airline/vim-airline'
     Plug 'vim-airline/vim-airline-themes'
     Plug 'kien/ctrlp.vim'
     Plug 'scrooloose/syntastic'
     Plug 'SirVer/ultisnips'
     Plug 'honza/vim-snippets'
     Plug 'valloric/youcompleteme'
call plug#end()
